### ISSUE TITLE
Error when redirecting

### ISSUE THREAD

**Issue by beliboba** [pyx/sanic-auth#19]
When i try to access route with @login_required and <tag> it takes me to the auth page but after login it takes me back to route but without tag, so it throws 404 error. When i try to access the route with tag via url it makes me enter password again and i get stuck

**Comment by pyx** [comment]
Could you post the code?

**Comment by beliboba** [comment]
![image](https://user-images.githubusercontent.com/73661136/162880310-951d731e-6afe-4754-92bd-799074685cbb.png)

**Comment by beliboba** [comment]
It also ignores redirect function

**Comment by beliboba** [comment]
Fixed
![image](https://user-images.githubusercontent.com/73661136/163395042-1768ee15-3976-47b7-b74f-91161bc2ab4e.png)
