### ISSUE TITLE
Using auth decorators in Class-Based Views

### ISSUE THREAD

**Issue by sreecodeslayer** [pyx/sanic-auth#4]
Sanic lets us use [Decorators](https://sanic.readthedocs.io/en/latest/sanic/class_based_views.html#decorators) in Class based Views,  this way. So, if my views are in `views.py`, how can I access the `auth.decorator_name` in those Classes? 
Am having trouble importing the `auth` defined in my `__init__.py`, or am I doing it wrong.

`__init__.py`:

```
.
.
app = Sanic(__name__)
app.config.AUTH_LOGIN_ENDPOINT = 'login'
.
.
auth = Auth(app)

@auth.serializer
def serializer(user):
	return {'id':str(user.id),'email':user.email,'name':user.username}

@auth.user_loader
def user_loader(user):
	return user

app.add_route(Login.as_view(),'/login')
app.add_route(Register.as_view(),'/signup')
```

`views.py`:

```
class Dashboard(HTTPMethodView):
	# decorators = [auth.login_required]
	async def dashboard(self, request):
		pass

```

**Comment by pyx** [comment]
It worked with this

app.py
```python
from sanic import Sanic
from sanic.views import HTTPMethodView
from sanic.response import text
from sanic_auth import Auth


app = Sanic(__name__)
app.config.AUTH_LOGIN_ENDPOINT = 'login'
auth = Auth(app)
session = {}


@app.middleware('request')
async def add_session(request):
    request['session'] = session


@app.route('/login')
async def login(request):
    return text('login form')


class Dashboard(HTTPMethodView):
    decorators = [auth.login_required]

    async def get(self, request):
        return text('off limits')


app.add_route(Dashboard.as_view(), '/')


if __name__ == '__main__':
    app.run(debug=True)
```

In your view class, are you sure the handler is named `dashboard`?  It should be `get` (for handling `GET` request) or it won't get called.

**Comment by sreecodeslayer** [comment]
Oops, sorry for the confusion, it was `get`, was my error copying it over here.

The problem is that I had the views set up in a different file, so the actual issue was due to improper import. Got it fixed by import View classes after setting up everything in the `__ini__.py`.
