### ISSUE TITLE
How sanic-auth could be integrated into Bluteprints?

### ISSUE THREAD

**Issue by tonyzhangcn** [pyx/sanic-auth#6]
Hello,
I'm organizing my project into many different Blueprints(the routes), and all the routes(ENDPOINTS) can be accessed only after auth is done. I'm trying to utilize sanic-auth to help but just found the example given in the doc seems only applied to a centralized route file, say main.py. How sanic-auth could be integrated to the projects as mine which is composed of different Blueprints? Thank you!

**Comment by pyx** [comment]
There are many ways to do it, one is to create a shared `auth` object somewhere isolated. I wrote a simple example here: https://github.com/pyx/sanic-auth/tree/master/examples/blueprint

**Comment by tonyzhangcn** [comment]
thank you for your reply, that helps😀
